/*
 * This file is generated by jOOQ.
 */
package com.databasir.api.persist.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Connection implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       schemaSourceId;
    private String        url;
    private String        username;
    private String        password;
    private LocalDateTime updateAt;
    private LocalDateTime createAt;

    public Connection() {}

    public Connection(Connection value) {
        this.id = value.id;
        this.schemaSourceId = value.schemaSourceId;
        this.url = value.url;
        this.username = value.username;
        this.password = value.password;
        this.updateAt = value.updateAt;
        this.createAt = value.createAt;
    }

    public Connection(
        Integer       id,
        Integer       schemaSourceId,
        String        url,
        String        username,
        String        password,
        LocalDateTime updateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.schemaSourceId = schemaSourceId;
        this.url = url;
        this.username = username;
        this.password = password;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.connection.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.connection.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.connection.schema_source_id</code>.
     */
    public Integer getSchemaSourceId() {
        return this.schemaSourceId;
    }

    /**
     * Setter for <code>databasir.connection.schema_source_id</code>.
     */
    public void setSchemaSourceId(Integer schemaSourceId) {
        this.schemaSourceId = schemaSourceId;
    }

    /**
     * Getter for <code>databasir.connection.url</code>.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>databasir.connection.url</code>.
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for <code>databasir.connection.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>databasir.connection.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>databasir.connection.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>databasir.connection.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>databasir.connection.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>databasir.connection.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>databasir.connection.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.connection.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Connection (");

        sb.append(id);
        sb.append(", ").append(schemaSourceId);
        sb.append(", ").append(url);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
