/*
 * This file is generated by jOOQ.
 */
package com.databasir.web.persist.tables.records;


import com.databasir.web.persist.tables.TableColumnMeta;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableColumnMetaRecord extends UpdatableRecordImpl<TableColumnMetaRecord> implements Record12<Integer, Integer, Integer, String, String, String, String, Integer, Integer, Boolean, Boolean, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.table_column_meta.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.table_column_meta.table_meta_id</code>.
     */
    public void setTableMetaId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.table_meta_id</code>.
     */
    public Integer getTableMetaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>databasir.table_column_meta.schema_meta_id</code>.
     */
    public void setSchemaMetaId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.schema_meta_id</code>.
     */
    public Integer getSchemaMetaId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>databasir.table_column_meta.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>databasir.table_column_meta.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>databasir.table_column_meta.comment</code>.
     */
    public void setComment(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.comment</code>.
     */
    public String getComment() {
        return (String) get(5);
    }

    /**
     * Setter for <code>databasir.table_column_meta.default_value</code>.
     */
    public void setDefaultValue(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.default_value</code>.
     */
    public String getDefaultValue() {
        return (String) get(6);
    }

    /**
     * Setter for <code>databasir.table_column_meta.size</code>.
     */
    public void setSize(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.size</code>.
     */
    public Integer getSize() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>databasir.table_column_meta.decimal_digits</code>.
     */
    public void setDecimalDigits(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.decimal_digits</code>.
     */
    public Integer getDecimalDigits() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>databasir.table_column_meta.is_nullable</code>.
     */
    public void setIsNullable(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.is_nullable</code>.
     */
    public Boolean getIsNullable() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>databasir.table_column_meta.is_auto_increment</code>.
     */
    public void setIsAutoIncrement(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.is_auto_increment</code>.
     */
    public Boolean getIsAutoIncrement() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>databasir.table_column_meta.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>databasir.table_column_meta.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Integer, Integer, String, String, String, String, Integer, Integer, Boolean, Boolean, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, Integer, Integer, String, String, String, String, Integer, Integer, Boolean, Boolean, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TableColumnMeta.TABLE_COLUMN_META.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TableColumnMeta.TABLE_COLUMN_META.TABLE_META_ID;
    }

    @Override
    public Field<Integer> field3() {
        return TableColumnMeta.TABLE_COLUMN_META.SCHEMA_META_ID;
    }

    @Override
    public Field<String> field4() {
        return TableColumnMeta.TABLE_COLUMN_META.NAME;
    }

    @Override
    public Field<String> field5() {
        return TableColumnMeta.TABLE_COLUMN_META.TYPE;
    }

    @Override
    public Field<String> field6() {
        return TableColumnMeta.TABLE_COLUMN_META.COMMENT;
    }

    @Override
    public Field<String> field7() {
        return TableColumnMeta.TABLE_COLUMN_META.DEFAULT_VALUE;
    }

    @Override
    public Field<Integer> field8() {
        return TableColumnMeta.TABLE_COLUMN_META.SIZE;
    }

    @Override
    public Field<Integer> field9() {
        return TableColumnMeta.TABLE_COLUMN_META.DECIMAL_DIGITS;
    }

    @Override
    public Field<Boolean> field10() {
        return TableColumnMeta.TABLE_COLUMN_META.IS_NULLABLE;
    }

    @Override
    public Field<Boolean> field11() {
        return TableColumnMeta.TABLE_COLUMN_META.IS_AUTO_INCREMENT;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return TableColumnMeta.TABLE_COLUMN_META.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTableMetaId();
    }

    @Override
    public Integer component3() {
        return getSchemaMetaId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getComment();
    }

    @Override
    public String component7() {
        return getDefaultValue();
    }

    @Override
    public Integer component8() {
        return getSize();
    }

    @Override
    public Integer component9() {
        return getDecimalDigits();
    }

    @Override
    public Boolean component10() {
        return getIsNullable();
    }

    @Override
    public Boolean component11() {
        return getIsAutoIncrement();
    }

    @Override
    public LocalDateTime component12() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTableMetaId();
    }

    @Override
    public Integer value3() {
        return getSchemaMetaId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getComment();
    }

    @Override
    public String value7() {
        return getDefaultValue();
    }

    @Override
    public Integer value8() {
        return getSize();
    }

    @Override
    public Integer value9() {
        return getDecimalDigits();
    }

    @Override
    public Boolean value10() {
        return getIsNullable();
    }

    @Override
    public Boolean value11() {
        return getIsAutoIncrement();
    }

    @Override
    public LocalDateTime value12() {
        return getCreateAt();
    }

    @Override
    public TableColumnMetaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value2(Integer value) {
        setTableMetaId(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value3(Integer value) {
        setSchemaMetaId(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value6(String value) {
        setComment(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value7(String value) {
        setDefaultValue(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value8(Integer value) {
        setSize(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value9(Integer value) {
        setDecimalDigits(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value10(Boolean value) {
        setIsNullable(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value11(Boolean value) {
        setIsAutoIncrement(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord value12(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public TableColumnMetaRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, Integer value8, Integer value9, Boolean value10, Boolean value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TableColumnMetaRecord
     */
    public TableColumnMetaRecord() {
        super(TableColumnMeta.TABLE_COLUMN_META);
    }

    /**
     * Create a detached, initialised TableColumnMetaRecord
     */
    public TableColumnMetaRecord(Integer id, Integer tableMetaId, Integer schemaMetaId, String name, String type, String comment, String defaultValue, Integer size, Integer decimalDigits, Boolean isNullable, Boolean isAutoIncrement, LocalDateTime createAt) {
        super(TableColumnMeta.TABLE_COLUMN_META);

        setId(id);
        setTableMetaId(tableMetaId);
        setSchemaMetaId(schemaMetaId);
        setName(name);
        setType(type);
        setComment(comment);
        setDefaultValue(defaultValue);
        setSize(size);
        setDecimalDigits(decimalDigits);
        setIsNullable(isNullable);
        setIsAutoIncrement(isAutoIncrement);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised TableColumnMetaRecord
     */
    public TableColumnMetaRecord(com.databasir.web.persist.tables.pojos.TableColumnMeta value) {
        super(TableColumnMeta.TABLE_COLUMN_META);

        if (value != null) {
            setId(value.getId());
            setTableMetaId(value.getTableMetaId());
            setSchemaMetaId(value.getSchemaMetaId());
            setName(value.getName());
            setType(value.getType());
            setComment(value.getComment());
            setDefaultValue(value.getDefaultValue());
            setSize(value.getSize());
            setDecimalDigits(value.getDecimalDigits());
            setIsNullable(value.getIsNullable());
            setIsAutoIncrement(value.getIsAutoIncrement());
            setCreateAt(value.getCreateAt());
        }
    }
}
