/*
 * This file is generated by jOOQ.
 */
package com.databasir.api.persist.tables.records;


import com.databasir.api.persist.tables.TableMeta;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableMetaRecord extends UpdatableRecordImpl<TableMetaRecord> implements Record6<Integer, Integer, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.table_meta.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.table_meta.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.table_meta.schema_meta_id</code>.
     */
    public void setSchemaMetaId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.table_meta.schema_meta_id</code>.
     */
    public Integer getSchemaMetaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>databasir.table_meta.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.table_meta.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>databasir.table_meta.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>databasir.table_meta.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>databasir.table_meta.comment</code>.
     */
    public void setComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>databasir.table_meta.comment</code>.
     */
    public String getComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>databasir.table_meta.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>databasir.table_meta.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TableMeta.TABLE_META.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TableMeta.TABLE_META.SCHEMA_META_ID;
    }

    @Override
    public Field<String> field3() {
        return TableMeta.TABLE_META.NAME;
    }

    @Override
    public Field<String> field4() {
        return TableMeta.TABLE_META.TYPE;
    }

    @Override
    public Field<String> field5() {
        return TableMeta.TABLE_META.COMMENT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TableMeta.TABLE_META.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSchemaMetaId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getComment();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSchemaMetaId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getComment();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateAt();
    }

    @Override
    public TableMetaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TableMetaRecord value2(Integer value) {
        setSchemaMetaId(value);
        return this;
    }

    @Override
    public TableMetaRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public TableMetaRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public TableMetaRecord value5(String value) {
        setComment(value);
        return this;
    }

    @Override
    public TableMetaRecord value6(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public TableMetaRecord values(Integer value1, Integer value2, String value3, String value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TableMetaRecord
     */
    public TableMetaRecord() {
        super(TableMeta.TABLE_META);
    }

    /**
     * Create a detached, initialised TableMetaRecord
     */
    public TableMetaRecord(Integer id, Integer schemaMetaId, String name, String type, String comment, LocalDateTime createAt) {
        super(TableMeta.TABLE_META);

        setId(id);
        setSchemaMetaId(schemaMetaId);
        setName(name);
        setType(type);
        setComment(comment);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised TableMetaRecord
     */
    public TableMetaRecord(com.databasir.api.persist.tables.pojos.TableMeta value) {
        super(TableMeta.TABLE_META);

        if (value != null) {
            setId(value.getId());
            setSchemaMetaId(value.getSchemaMetaId());
            setName(value.getName());
            setType(value.getType());
            setComment(value.getComment());
            setCreateAt(value.getCreateAt());
        }
    }
}
