/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private String        expression;
    private String        path;
    private LocalDateTime updateAt;
    private LocalDateTime createAt;

    public PermissionPojo() {}

    public PermissionPojo(PermissionPojo value) {
        this.id = value.id;
        this.name = value.name;
        this.expression = value.expression;
        this.path = value.path;
        this.updateAt = value.updateAt;
        this.createAt = value.createAt;
    }

    public PermissionPojo(
        Integer       id,
        String        name,
        String        expression,
        String        path,
        LocalDateTime updateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.name = name;
        this.expression = expression;
        this.path = path;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.permission.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.permission.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.permission.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>databasir.permission.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>databasir.permission.expression</code>.
     */
    public String getExpression() {
        return this.expression;
    }

    /**
     * Setter for <code>databasir.permission.expression</code>.
     */
    public void setExpression(String expression) {
        this.expression = expression;
    }

    /**
     * Getter for <code>databasir.permission.path</code>.
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>databasir.permission.path</code>.
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for <code>databasir.permission.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>databasir.permission.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>databasir.permission.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.permission.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PermissionPojo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(expression);
        sb.append(", ").append(path);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
