/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private Boolean       isBasic;
    private Boolean       deleted;
    private LocalDateTime updateAt;
    private LocalDateTime createAt;

    public RolePojo() {}

    public RolePojo(RolePojo value) {
        this.id = value.id;
        this.name = value.name;
        this.isBasic = value.isBasic;
        this.deleted = value.deleted;
        this.updateAt = value.updateAt;
        this.createAt = value.createAt;
    }

    public RolePojo(
        Integer       id,
        String        name,
        Boolean       isBasic,
        Boolean       deleted,
        LocalDateTime updateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.name = name;
        this.isBasic = isBasic;
        this.deleted = deleted;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.role.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.role.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.role.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>databasir.role.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>databasir.role.is_basic</code>.
     */
    public Boolean getIsBasic() {
        return this.isBasic;
    }

    /**
     * Setter for <code>databasir.role.is_basic</code>.
     */
    public void setIsBasic(Boolean isBasic) {
        this.isBasic = isBasic;
    }

    /**
     * Getter for <code>databasir.role.deleted</code>.
     */
    public Boolean getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>databasir.role.deleted</code>.
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * Getter for <code>databasir.role.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>databasir.role.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>databasir.role.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.role.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RolePojo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(isBasic);
        sb.append(", ").append(deleted);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
