/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermissionPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       roleId;
    private Integer       permissionId;
    private LocalDateTime createAt;

    public RolePermissionPojo() {}

    public RolePermissionPojo(RolePermissionPojo value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.permissionId = value.permissionId;
        this.createAt = value.createAt;
    }

    public RolePermissionPojo(
        Integer       id,
        Integer       roleId,
        Integer       permissionId,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.roleId = roleId;
        this.permissionId = permissionId;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.role_permission.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.role_permission.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.role_permission.role_id</code>.
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>databasir.role_permission.role_id</code>.
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>databasir.role_permission.permission_id</code>.
     */
    public Integer getPermissionId() {
        return this.permissionId;
    }

    /**
     * Setter for <code>databasir.role_permission.permission_id</code>.
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * Getter for <code>databasir.role_permission.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.role_permission.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RolePermissionPojo (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(permissionId);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
