/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaMetaPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       schemaSourceId;
    private String        name;
    private String        productName;
    private String        productVersion;
    private Long          version;
    private LocalDateTime updateAt;
    private LocalDateTime createAt;

    public SchemaMetaPojo() {}

    public SchemaMetaPojo(SchemaMetaPojo value) {
        this.id = value.id;
        this.schemaSourceId = value.schemaSourceId;
        this.name = value.name;
        this.productName = value.productName;
        this.productVersion = value.productVersion;
        this.version = value.version;
        this.updateAt = value.updateAt;
        this.createAt = value.createAt;
    }

    public SchemaMetaPojo(
        Integer       id,
        Integer       schemaSourceId,
        String        name,
        String        productName,
        String        productVersion,
        Long          version,
        LocalDateTime updateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.schemaSourceId = schemaSourceId;
        this.name = name;
        this.productName = productName;
        this.productVersion = productVersion;
        this.version = version;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.schema_meta.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.schema_meta.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.schema_meta.schema_source_id</code>.
     */
    public Integer getSchemaSourceId() {
        return this.schemaSourceId;
    }

    /**
     * Setter for <code>databasir.schema_meta.schema_source_id</code>.
     */
    public void setSchemaSourceId(Integer schemaSourceId) {
        this.schemaSourceId = schemaSourceId;
    }

    /**
     * Getter for <code>databasir.schema_meta.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>databasir.schema_meta.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>databasir.schema_meta.product_name</code>.
     */
    public String getProductName() {
        return this.productName;
    }

    /**
     * Setter for <code>databasir.schema_meta.product_name</code>.
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Getter for <code>databasir.schema_meta.product_version</code>.
     */
    public String getProductVersion() {
        return this.productVersion;
    }

    /**
     * Setter for <code>databasir.schema_meta.product_version</code>.
     */
    public void setProductVersion(String productVersion) {
        this.productVersion = productVersion;
    }

    /**
     * Getter for <code>databasir.schema_meta.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>databasir.schema_meta.version</code>.
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for <code>databasir.schema_meta.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>databasir.schema_meta.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>databasir.schema_meta.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.schema_meta.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SchemaMetaPojo (");

        sb.append(id);
        sb.append(", ").append(schemaSourceId);
        sb.append(", ").append(name);
        sb.append(", ").append(productName);
        sb.append(", ").append(productVersion);
        sb.append(", ").append(version);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
