/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRolePojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       userId;
    private Integer       roleId;
    private LocalDateTime createAt;

    public UserRolePojo() {}

    public UserRolePojo(UserRolePojo value) {
        this.id = value.id;
        this.userId = value.userId;
        this.roleId = value.roleId;
        this.createAt = value.createAt;
    }

    public UserRolePojo(
        Integer       id,
        Integer       userId,
        Integer       roleId,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.user_role.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.user_role.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.user_role.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>databasir.user_role.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>databasir.user_role.role_id</code>.
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>databasir.user_role.role_id</code>.
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>databasir.user_role.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.user_role.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRolePojo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
