/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.records;


import com.databasir.dao.tables.Permission;
import com.databasir.dao.tables.pojos.PermissionPojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionRecord extends UpdatableRecordImpl<PermissionRecord> implements Record6<Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.permission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.permission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.permission.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.permission.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>databasir.permission.expression</code>.
     */
    public void setExpression(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.permission.expression</code>.
     */
    public String getExpression() {
        return (String) get(2);
    }

    /**
     * Setter for <code>databasir.permission.path</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>databasir.permission.path</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>databasir.permission.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>databasir.permission.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>databasir.permission.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>databasir.permission.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Permission.PERMISSION.ID;
    }

    @Override
    public Field<String> field2() {
        return Permission.PERMISSION.NAME;
    }

    @Override
    public Field<String> field3() {
        return Permission.PERMISSION.EXPRESSION;
    }

    @Override
    public Field<String> field4() {
        return Permission.PERMISSION.PATH;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Permission.PERMISSION.UPDATE_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Permission.PERMISSION.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getExpression();
    }

    @Override
    public String component4() {
        return getPath();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateAt();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getExpression();
    }

    @Override
    public String value4() {
        return getPath();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateAt();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateAt();
    }

    @Override
    public PermissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PermissionRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PermissionRecord value3(String value) {
        setExpression(value);
        return this;
    }

    @Override
    public PermissionRecord value4(String value) {
        setPath(value);
        return this;
    }

    @Override
    public PermissionRecord value5(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public PermissionRecord value6(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public PermissionRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionRecord
     */
    public PermissionRecord() {
        super(Permission.PERMISSION);
    }

    /**
     * Create a detached, initialised PermissionRecord
     */
    public PermissionRecord(Integer id, String name, String expression, String path, LocalDateTime updateAt, LocalDateTime createAt) {
        super(Permission.PERMISSION);

        setId(id);
        setName(name);
        setExpression(expression);
        setPath(path);
        setUpdateAt(updateAt);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised PermissionRecord
     */
    public PermissionRecord(PermissionPojo value) {
        super(Permission.PERMISSION);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setExpression(value.getExpression());
            setPath(value.getPath());
            setUpdateAt(value.getUpdateAt());
            setCreateAt(value.getCreateAt());
        }
    }
}
