/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.records;


import com.databasir.dao.tables.RolePermission;
import com.databasir.dao.tables.pojos.RolePermissionPojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermissionRecord extends UpdatableRecordImpl<RolePermissionRecord> implements Record4<Integer, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.role_permission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.role_permission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.role_permission.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.role_permission.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>databasir.role_permission.permission_id</code>.
     */
    public void setPermissionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.role_permission.permission_id</code>.
     */
    public Integer getPermissionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>databasir.role_permission.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>databasir.role_permission.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RolePermission.ROLE_PERMISSION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return RolePermission.ROLE_PERMISSION.ROLE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return RolePermission.ROLE_PERMISSION.PERMISSION_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return RolePermission.ROLE_PERMISSION.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRoleId();
    }

    @Override
    public Integer component3() {
        return getPermissionId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRoleId();
    }

    @Override
    public Integer value3() {
        return getPermissionId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateAt();
    }

    @Override
    public RolePermissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RolePermissionRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolePermissionRecord value3(Integer value) {
        setPermissionId(value);
        return this;
    }

    @Override
    public RolePermissionRecord value4(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public RolePermissionRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePermissionRecord
     */
    public RolePermissionRecord() {
        super(RolePermission.ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised RolePermissionRecord
     */
    public RolePermissionRecord(Integer id, Integer roleId, Integer permissionId, LocalDateTime createAt) {
        super(RolePermission.ROLE_PERMISSION);

        setId(id);
        setRoleId(roleId);
        setPermissionId(permissionId);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised RolePermissionRecord
     */
    public RolePermissionRecord(RolePermissionPojo value) {
        super(RolePermission.ROLE_PERMISSION);

        if (value != null) {
            setId(value.getId());
            setRoleId(value.getRoleId());
            setPermissionId(value.getPermissionId());
            setCreateAt(value.getCreateAt());
        }
    }
}
