/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.records;


import com.databasir.dao.tables.SchemaMetaHistory;
import com.databasir.dao.tables.pojos.SchemaMetaHistoryPojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaMetaHistoryRecord extends UpdatableRecordImpl<SchemaMetaHistoryRecord> implements Record6<Integer, Integer, Integer, JSON, Long, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.schema_meta_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.schema_meta_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.schema_meta_history.schema_source_id</code>.
     */
    public void setSchemaSourceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.schema_meta_history.schema_source_id</code>.
     */
    public Integer getSchemaSourceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>databasir.schema_meta_history.schema_meta_id</code>.
     */
    public void setSchemaMetaId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.schema_meta_history.schema_meta_id</code>.
     */
    public Integer getSchemaMetaId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>databasir.schema_meta_history.schema_meta_object</code>.
     */
    public void setSchemaMetaObject(JSON value) {
        set(3, value);
    }

    /**
     * Getter for <code>databasir.schema_meta_history.schema_meta_object</code>.
     */
    public JSON getSchemaMetaObject() {
        return (JSON) get(3);
    }

    /**
     * Setter for <code>databasir.schema_meta_history.version</code>.
     */
    public void setVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>databasir.schema_meta_history.version</code>.
     */
    public Long getVersion() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>databasir.schema_meta_history.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>databasir.schema_meta_history.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, JSON, Long, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, JSON, Long, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SchemaMetaHistory.SCHEMA_META_HISTORY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return SchemaMetaHistory.SCHEMA_META_HISTORY.SCHEMA_SOURCE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return SchemaMetaHistory.SCHEMA_META_HISTORY.SCHEMA_META_ID;
    }

    @Override
    public Field<JSON> field4() {
        return SchemaMetaHistory.SCHEMA_META_HISTORY.SCHEMA_META_OBJECT;
    }

    @Override
    public Field<Long> field5() {
        return SchemaMetaHistory.SCHEMA_META_HISTORY.VERSION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SchemaMetaHistory.SCHEMA_META_HISTORY.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSchemaSourceId();
    }

    @Override
    public Integer component3() {
        return getSchemaMetaId();
    }

    @Override
    public JSON component4() {
        return getSchemaMetaObject();
    }

    @Override
    public Long component5() {
        return getVersion();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSchemaSourceId();
    }

    @Override
    public Integer value3() {
        return getSchemaMetaId();
    }

    @Override
    public JSON value4() {
        return getSchemaMetaObject();
    }

    @Override
    public Long value5() {
        return getVersion();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateAt();
    }

    @Override
    public SchemaMetaHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SchemaMetaHistoryRecord value2(Integer value) {
        setSchemaSourceId(value);
        return this;
    }

    @Override
    public SchemaMetaHistoryRecord value3(Integer value) {
        setSchemaMetaId(value);
        return this;
    }

    @Override
    public SchemaMetaHistoryRecord value4(JSON value) {
        setSchemaMetaObject(value);
        return this;
    }

    @Override
    public SchemaMetaHistoryRecord value5(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public SchemaMetaHistoryRecord value6(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public SchemaMetaHistoryRecord values(Integer value1, Integer value2, Integer value3, JSON value4, Long value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchemaMetaHistoryRecord
     */
    public SchemaMetaHistoryRecord() {
        super(SchemaMetaHistory.SCHEMA_META_HISTORY);
    }

    /**
     * Create a detached, initialised SchemaMetaHistoryRecord
     */
    public SchemaMetaHistoryRecord(Integer id, Integer schemaSourceId, Integer schemaMetaId, JSON schemaMetaObject, Long version, LocalDateTime createAt) {
        super(SchemaMetaHistory.SCHEMA_META_HISTORY);

        setId(id);
        setSchemaSourceId(schemaSourceId);
        setSchemaMetaId(schemaMetaId);
        setSchemaMetaObject(schemaMetaObject);
        setVersion(version);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised SchemaMetaHistoryRecord
     */
    public SchemaMetaHistoryRecord(SchemaMetaHistoryPojo value) {
        super(SchemaMetaHistory.SCHEMA_META_HISTORY);

        if (value != null) {
            setId(value.getId());
            setSchemaSourceId(value.getSchemaSourceId());
            setSchemaMetaId(value.getSchemaMetaId());
            setSchemaMetaObject(value.getSchemaMetaObject());
            setVersion(value.getVersion());
            setCreateAt(value.getCreateAt());
        }
    }
}
