/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.records;


import com.databasir.dao.tables.TableIndexMeta;
import com.databasir.dao.tables.pojos.TableIndexMetaPojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableIndexMetaRecord extends UpdatableRecordImpl<TableIndexMetaRecord> implements Record8<Integer, Integer, Integer, String, Boolean, Boolean, JSON, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.table_index_meta.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.table_index_meta.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.table_index_meta.table_meta_id</code>.
     */
    public void setTableMetaId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.table_index_meta.table_meta_id</code>.
     */
    public Integer getTableMetaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>databasir.table_index_meta.schema_meta_id</code>.
     */
    public void setSchemaMetaId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.table_index_meta.schema_meta_id</code>.
     */
    public Integer getSchemaMetaId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>databasir.table_index_meta.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>databasir.table_index_meta.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>databasir.table_index_meta.is_primary</code>.
     */
    public void setIsPrimary(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>databasir.table_index_meta.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>databasir.table_index_meta.is_unique</code>.
     */
    public void setIsUnique(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>databasir.table_index_meta.is_unique</code>.
     */
    public Boolean getIsUnique() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>databasir.table_index_meta.column_name_array</code>.
     */
    public void setColumnNameArray(JSON value) {
        set(6, value);
    }

    /**
     * Getter for <code>databasir.table_index_meta.column_name_array</code>.
     */
    public JSON getColumnNameArray() {
        return (JSON) get(6);
    }

    /**
     * Setter for <code>databasir.table_index_meta.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>databasir.table_index_meta.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, String, Boolean, Boolean, JSON, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, String, Boolean, Boolean, JSON, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TableIndexMeta.TABLE_INDEX_META.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TableIndexMeta.TABLE_INDEX_META.TABLE_META_ID;
    }

    @Override
    public Field<Integer> field3() {
        return TableIndexMeta.TABLE_INDEX_META.SCHEMA_META_ID;
    }

    @Override
    public Field<String> field4() {
        return TableIndexMeta.TABLE_INDEX_META.NAME;
    }

    @Override
    public Field<Boolean> field5() {
        return TableIndexMeta.TABLE_INDEX_META.IS_PRIMARY;
    }

    @Override
    public Field<Boolean> field6() {
        return TableIndexMeta.TABLE_INDEX_META.IS_UNIQUE;
    }

    @Override
    public Field<JSON> field7() {
        return TableIndexMeta.TABLE_INDEX_META.COLUMN_NAME_ARRAY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TableIndexMeta.TABLE_INDEX_META.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTableMetaId();
    }

    @Override
    public Integer component3() {
        return getSchemaMetaId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Boolean component5() {
        return getIsPrimary();
    }

    @Override
    public Boolean component6() {
        return getIsUnique();
    }

    @Override
    public JSON component7() {
        return getColumnNameArray();
    }

    @Override
    public LocalDateTime component8() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTableMetaId();
    }

    @Override
    public Integer value3() {
        return getSchemaMetaId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Boolean value5() {
        return getIsPrimary();
    }

    @Override
    public Boolean value6() {
        return getIsUnique();
    }

    @Override
    public JSON value7() {
        return getColumnNameArray();
    }

    @Override
    public LocalDateTime value8() {
        return getCreateAt();
    }

    @Override
    public TableIndexMetaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TableIndexMetaRecord value2(Integer value) {
        setTableMetaId(value);
        return this;
    }

    @Override
    public TableIndexMetaRecord value3(Integer value) {
        setSchemaMetaId(value);
        return this;
    }

    @Override
    public TableIndexMetaRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public TableIndexMetaRecord value5(Boolean value) {
        setIsPrimary(value);
        return this;
    }

    @Override
    public TableIndexMetaRecord value6(Boolean value) {
        setIsUnique(value);
        return this;
    }

    @Override
    public TableIndexMetaRecord value7(JSON value) {
        setColumnNameArray(value);
        return this;
    }

    @Override
    public TableIndexMetaRecord value8(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public TableIndexMetaRecord values(Integer value1, Integer value2, Integer value3, String value4, Boolean value5, Boolean value6, JSON value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TableIndexMetaRecord
     */
    public TableIndexMetaRecord() {
        super(TableIndexMeta.TABLE_INDEX_META);
    }

    /**
     * Create a detached, initialised TableIndexMetaRecord
     */
    public TableIndexMetaRecord(Integer id, Integer tableMetaId, Integer schemaMetaId, String name, Boolean isPrimary, Boolean isUnique, JSON columnNameArray, LocalDateTime createAt) {
        super(TableIndexMeta.TABLE_INDEX_META);

        setId(id);
        setTableMetaId(tableMetaId);
        setSchemaMetaId(schemaMetaId);
        setName(name);
        setIsPrimary(isPrimary);
        setIsUnique(isUnique);
        setColumnNameArray(columnNameArray);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised TableIndexMetaRecord
     */
    public TableIndexMetaRecord(TableIndexMetaPojo value) {
        super(TableIndexMeta.TABLE_INDEX_META);

        if (value != null) {
            setId(value.getId());
            setTableMetaId(value.getTableMetaId());
            setSchemaMetaId(value.getSchemaMetaId());
            setName(value.getName());
            setIsPrimary(value.getIsPrimary());
            setIsUnique(value.getIsUnique());
            setColumnNameArray(value.getColumnNameArray());
            setCreateAt(value.getCreateAt());
        }
    }
}
