/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.records;


import com.databasir.dao.tables.UserRole;
import com.databasir.dao.tables.pojos.UserRolePojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleRecord extends UpdatableRecordImpl<UserRoleRecord> implements Record4<Integer, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.user_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.user_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.user_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.user_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>databasir.user_role.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.user_role.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>databasir.user_role.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>databasir.user_role.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserRole.USER_ROLE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return UserRole.USER_ROLE.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return UserRole.USER_ROLE.ROLE_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return UserRole.USER_ROLE.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getRoleId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getRoleId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateAt();
    }

    @Override
    public UserRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRoleRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserRoleRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public UserRoleRecord value4(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public UserRoleRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(UserRole.USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(Integer id, Integer userId, Integer roleId, LocalDateTime createAt) {
        super(UserRole.USER_ROLE);

        setId(id);
        setUserId(userId);
        setRoleId(roleId);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(UserRolePojo value) {
        super(UserRole.USER_ROLE);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setRoleId(value.getRoleId());
            setCreateAt(value.getCreateAt());
        }
    }
}
