/*
 * This file is generated by jOOQ.
 */
package com.databasir.web.persist.tables;


import com.databasir.web.persist.Databasir;
import com.databasir.web.persist.Keys;
import com.databasir.web.persist.tables.records.TableTriggerMetaRecord;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableTriggerMeta extends TableImpl<TableTriggerMetaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>databasir.table_trigger_meta</code>
     */
    public static final TableTriggerMeta TABLE_TRIGGER_META = new TableTriggerMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TableTriggerMetaRecord> getRecordType() {
        return TableTriggerMetaRecord.class;
    }

    /**
     * The column <code>databasir.table_trigger_meta.id</code>.
     */
    public final TableField<TableTriggerMetaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>databasir.table_trigger_meta.table_meta_id</code>.
     */
    public final TableField<TableTriggerMetaRecord, Integer> TABLE_META_ID = createField(DSL.name("table_meta_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>databasir.table_trigger_meta.schema_meta_id</code>.
     */
    public final TableField<TableTriggerMetaRecord, Integer> SCHEMA_META_ID = createField(DSL.name("schema_meta_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>databasir.table_trigger_meta.timing</code>.
     */
    public final TableField<TableTriggerMetaRecord, String> TIMING = createField(DSL.name("timing"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>databasir.table_trigger_meta.manipulation</code>.
     */
    public final TableField<TableTriggerMetaRecord, String> MANIPULATION = createField(DSL.name("manipulation"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>databasir.table_trigger_meta.statement</code>.
     */
    public final TableField<TableTriggerMetaRecord, String> STATEMENT = createField(DSL.name("statement"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>databasir.table_trigger_meta.trigger_create_at</code>.
     */
    public final TableField<TableTriggerMetaRecord, String> TRIGGER_CREATE_AT = createField(DSL.name("trigger_create_at"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>databasir.table_trigger_meta.create_at</code>.
     */
    public final TableField<TableTriggerMetaRecord, LocalDateTime> CREATE_AT = createField(DSL.name("create_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private TableTriggerMeta(Name alias, Table<TableTriggerMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private TableTriggerMeta(Name alias, Table<TableTriggerMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>databasir.table_trigger_meta</code> table
     * reference
     */
    public TableTriggerMeta(String alias) {
        this(DSL.name(alias), TABLE_TRIGGER_META);
    }

    /**
     * Create an aliased <code>databasir.table_trigger_meta</code> table
     * reference
     */
    public TableTriggerMeta(Name alias) {
        this(alias, TABLE_TRIGGER_META);
    }

    /**
     * Create a <code>databasir.table_trigger_meta</code> table reference
     */
    public TableTriggerMeta() {
        this(DSL.name("table_trigger_meta"), null);
    }

    public <O extends Record> TableTriggerMeta(Table<O> child, ForeignKey<O, TableTriggerMetaRecord> key) {
        super(child, key, TABLE_TRIGGER_META);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Databasir.DATABASIR;
    }

    @Override
    public Identity<TableTriggerMetaRecord, Integer> getIdentity() {
        return (Identity<TableTriggerMetaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TableTriggerMetaRecord> getPrimaryKey() {
        return Keys.KEY_TABLE_TRIGGER_META_PRIMARY;
    }

    @Override
    public TableTriggerMeta as(String alias) {
        return new TableTriggerMeta(DSL.name(alias), this);
    }

    @Override
    public TableTriggerMeta as(Name alias) {
        return new TableTriggerMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TableTriggerMeta rename(String name) {
        return new TableTriggerMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TableTriggerMeta rename(Name name) {
        return new TableTriggerMeta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
