/*
 * This file is generated by jOOQ.
 */
package com.databasir.web.persist.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectionProperty implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       connectionId;
    private String        key;
    private String        value;
    private LocalDateTime createAt;

    public ConnectionProperty() {}

    public ConnectionProperty(ConnectionProperty value) {
        this.id = value.id;
        this.connectionId = value.connectionId;
        this.key = value.key;
        this.value = value.value;
        this.createAt = value.createAt;
    }

    public ConnectionProperty(
        Integer       id,
        Integer       connectionId,
        String        key,
        String        value,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.connectionId = connectionId;
        this.key = key;
        this.value = value;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.connection_property.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.connection_property.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.connection_property.connection_id</code>.
     */
    public Integer getConnectionId() {
        return this.connectionId;
    }

    /**
     * Setter for <code>databasir.connection_property.connection_id</code>.
     */
    public void setConnectionId(Integer connectionId) {
        this.connectionId = connectionId;
    }

    /**
     * Getter for <code>databasir.connection_property.key</code>.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>databasir.connection_property.key</code>.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>databasir.connection_property.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>databasir.connection_property.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for <code>databasir.connection_property.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.connection_property.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConnectionProperty (");

        sb.append(id);
        sb.append(", ").append(connectionId);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
