/*
 * This file is generated by jOOQ.
 */
package com.databasir.web.persist.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaSourceTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       schemaSourceId;
    private Integer       tagId;
    private LocalDateTime createAt;

    public SchemaSourceTag() {}

    public SchemaSourceTag(SchemaSourceTag value) {
        this.id = value.id;
        this.schemaSourceId = value.schemaSourceId;
        this.tagId = value.tagId;
        this.createAt = value.createAt;
    }

    public SchemaSourceTag(
        Integer       id,
        Integer       schemaSourceId,
        Integer       tagId,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.schemaSourceId = schemaSourceId;
        this.tagId = tagId;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.schema_source_tag.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.schema_source_tag.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.schema_source_tag.schema_source_id</code>.
     */
    public Integer getSchemaSourceId() {
        return this.schemaSourceId;
    }

    /**
     * Setter for <code>databasir.schema_source_tag.schema_source_id</code>.
     */
    public void setSchemaSourceId(Integer schemaSourceId) {
        this.schemaSourceId = schemaSourceId;
    }

    /**
     * Getter for <code>databasir.schema_source_tag.tag_id</code>.
     */
    public Integer getTagId() {
        return this.tagId;
    }

    /**
     * Setter for <code>databasir.schema_source_tag.tag_id</code>.
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * Getter for <code>databasir.schema_source_tag.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.schema_source_tag.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SchemaSourceTag (");

        sb.append(id);
        sb.append(", ").append(schemaSourceId);
        sb.append(", ").append(tagId);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
