/*
 * This file is generated by jOOQ.
 */
package com.databasir.web.persist.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableIndexMeta implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       tableMetaId;
    private Integer       schemaMetaId;
    private String        name;
    private Boolean       isPrimary;
    private Boolean       isUnique;
    private JSON          columnNameArray;
    private LocalDateTime createAt;

    public TableIndexMeta() {}

    public TableIndexMeta(TableIndexMeta value) {
        this.id = value.id;
        this.tableMetaId = value.tableMetaId;
        this.schemaMetaId = value.schemaMetaId;
        this.name = value.name;
        this.isPrimary = value.isPrimary;
        this.isUnique = value.isUnique;
        this.columnNameArray = value.columnNameArray;
        this.createAt = value.createAt;
    }

    public TableIndexMeta(
        Integer       id,
        Integer       tableMetaId,
        Integer       schemaMetaId,
        String        name,
        Boolean       isPrimary,
        Boolean       isUnique,
        JSON          columnNameArray,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.tableMetaId = tableMetaId;
        this.schemaMetaId = schemaMetaId;
        this.name = name;
        this.isPrimary = isPrimary;
        this.isUnique = isUnique;
        this.columnNameArray = columnNameArray;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.table_index_meta.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.table_index_meta.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.table_index_meta.table_meta_id</code>.
     */
    public Integer getTableMetaId() {
        return this.tableMetaId;
    }

    /**
     * Setter for <code>databasir.table_index_meta.table_meta_id</code>.
     */
    public void setTableMetaId(Integer tableMetaId) {
        this.tableMetaId = tableMetaId;
    }

    /**
     * Getter for <code>databasir.table_index_meta.schema_meta_id</code>.
     */
    public Integer getSchemaMetaId() {
        return this.schemaMetaId;
    }

    /**
     * Setter for <code>databasir.table_index_meta.schema_meta_id</code>.
     */
    public void setSchemaMetaId(Integer schemaMetaId) {
        this.schemaMetaId = schemaMetaId;
    }

    /**
     * Getter for <code>databasir.table_index_meta.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>databasir.table_index_meta.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>databasir.table_index_meta.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }

    /**
     * Setter for <code>databasir.table_index_meta.is_primary</code>.
     */
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }

    /**
     * Getter for <code>databasir.table_index_meta.is_unique</code>.
     */
    public Boolean getIsUnique() {
        return this.isUnique;
    }

    /**
     * Setter for <code>databasir.table_index_meta.is_unique</code>.
     */
    public void setIsUnique(Boolean isUnique) {
        this.isUnique = isUnique;
    }

    /**
     * Getter for <code>databasir.table_index_meta.column_name_array</code>.
     */
    public JSON getColumnNameArray() {
        return this.columnNameArray;
    }

    /**
     * Setter for <code>databasir.table_index_meta.column_name_array</code>.
     */
    public void setColumnNameArray(JSON columnNameArray) {
        this.columnNameArray = columnNameArray;
    }

    /**
     * Getter for <code>databasir.table_index_meta.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.table_index_meta.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TableIndexMeta (");

        sb.append(id);
        sb.append(", ").append(tableMetaId);
        sb.append(", ").append(schemaMetaId);
        sb.append(", ").append(name);
        sb.append(", ").append(isPrimary);
        sb.append(", ").append(isUnique);
        sb.append(", ").append(columnNameArray);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
