/*
 * This file is generated by jOOQ.
 */
package com.databasir.web.persist.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableMeta implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       schemaMetaId;
    private String        name;
    private String        type;
    private String        comment;
    private LocalDateTime createAt;

    public TableMeta() {}

    public TableMeta(TableMeta value) {
        this.id = value.id;
        this.schemaMetaId = value.schemaMetaId;
        this.name = value.name;
        this.type = value.type;
        this.comment = value.comment;
        this.createAt = value.createAt;
    }

    public TableMeta(
        Integer       id,
        Integer       schemaMetaId,
        String        name,
        String        type,
        String        comment,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.schemaMetaId = schemaMetaId;
        this.name = name;
        this.type = type;
        this.comment = comment;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.table_meta.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.table_meta.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.table_meta.schema_meta_id</code>.
     */
    public Integer getSchemaMetaId() {
        return this.schemaMetaId;
    }

    /**
     * Setter for <code>databasir.table_meta.schema_meta_id</code>.
     */
    public void setSchemaMetaId(Integer schemaMetaId) {
        this.schemaMetaId = schemaMetaId;
    }

    /**
     * Getter for <code>databasir.table_meta.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>databasir.table_meta.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>databasir.table_meta.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>databasir.table_meta.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>databasir.table_meta.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>databasir.table_meta.comment</code>.
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for <code>databasir.table_meta.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.table_meta.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TableMeta (");

        sb.append(id);
        sb.append(", ").append(schemaMetaId);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(comment);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
