/*
 * This file is generated by jOOQ.
 */
package com.databasir.web.persist.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tag implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private LocalDateTime createAt;

    public Tag() {}

    public Tag(Tag value) {
        this.id = value.id;
        this.name = value.name;
        this.createAt = value.createAt;
    }

    public Tag(
        Integer       id,
        String        name,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.name = name;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.tag.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.tag.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.tag.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>databasir.tag.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>databasir.tag.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.tag.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tag (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
