/*
 * This file is generated by jOOQ.
 */
package com.databasir.web.persist;


import com.databasir.web.persist.tables.Connection;
import com.databasir.web.persist.tables.ConnectionProperty;
import com.databasir.web.persist.tables.SchemaMeta;
import com.databasir.web.persist.tables.SchemaMetaHistory;
import com.databasir.web.persist.tables.SchemaSource;
import com.databasir.web.persist.tables.SchemaSourceMetaRule;
import com.databasir.web.persist.tables.SchemaSourceTag;
import com.databasir.web.persist.tables.TableColumnMeta;
import com.databasir.web.persist.tables.TableIndexMeta;
import com.databasir.web.persist.tables.TableMeta;
import com.databasir.web.persist.tables.TableTriggerMeta;
import com.databasir.web.persist.tables.Tag;


/**
 * Convenience access to all tables in databasir.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>databasir.connection</code>.
     */
    public static final Connection CONNECTION = Connection.CONNECTION;

    /**
     * The table <code>databasir.connection_property</code>.
     */
    public static final ConnectionProperty CONNECTION_PROPERTY = ConnectionProperty.CONNECTION_PROPERTY;

    /**
     * The table <code>databasir.schema_meta</code>.
     */
    public static final SchemaMeta SCHEMA_META = SchemaMeta.SCHEMA_META;

    /**
     * The table <code>databasir.schema_meta_history</code>.
     */
    public static final SchemaMetaHistory SCHEMA_META_HISTORY = SchemaMetaHistory.SCHEMA_META_HISTORY;

    /**
     * The table <code>databasir.schema_source</code>.
     */
    public static final SchemaSource SCHEMA_SOURCE = SchemaSource.SCHEMA_SOURCE;

    /**
     * The table <code>databasir.schema_source_meta_rule</code>.
     */
    public static final SchemaSourceMetaRule SCHEMA_SOURCE_META_RULE = SchemaSourceMetaRule.SCHEMA_SOURCE_META_RULE;

    /**
     * The table <code>databasir.schema_source_tag</code>.
     */
    public static final SchemaSourceTag SCHEMA_SOURCE_TAG = SchemaSourceTag.SCHEMA_SOURCE_TAG;

    /**
     * The table <code>databasir.table_column_meta</code>.
     */
    public static final TableColumnMeta TABLE_COLUMN_META = TableColumnMeta.TABLE_COLUMN_META;

    /**
     * The table <code>databasir.table_index_meta</code>.
     */
    public static final TableIndexMeta TABLE_INDEX_META = TableIndexMeta.TABLE_INDEX_META;

    /**
     * The table <code>databasir.table_meta</code>.
     */
    public static final TableMeta TABLE_META = TableMeta.TABLE_META;

    /**
     * The table <code>databasir.table_trigger_meta</code>.
     */
    public static final TableTriggerMeta TABLE_TRIGGER_META = TableTriggerMeta.TABLE_TRIGGER_META;

    /**
     * The table <code>databasir.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;
}
